---
title: "Study Two: Confirmatory Data Analysis"
author: "Joel Larwood"
date: "2019-09-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r processdata, message = FALSE}
library(tidyverse)
library(sjlabelled)

s2raw <- read_csv("data/s2.csv")

names(s2raw)


s2 <- s2raw %>% 
  mutate(rrq_6 = 6 - rrq_6,
         rrq_9 = 6 - rrq_9,
         rrq_10 = 6 - rrq_10,
         musebaq = rowSums(dplyr::select(., musebaq_1:musebaq_9)),
         Baseline = rowSums(dplyr::select(., deq_1_1:deq_1_4)),
         PostInduction = rowSums(dplyr::select(., deq_2_1: deq_2_4)),
         PostListening = rowSums(dplyr::select(., deq_3_1: deq_3_4)), 
         dif = PostListening - PostInduction
         ) 


s2 <- s2 %>% 
  mutate(rumination = rowMeans(dplyr::select(., rrq_1:rrq_12)), na.rm = FALSE)

s2 %>% 
  dplyr::select(Baseline,
                PostInduction,
                PostListening,
                rumination,
                musebaq,
                hours.listen,
                reg.use_1,
                age) %>% 
  psych::describe()

write_csv(s2, "data/s2Processed.csv")

# s2 %>% var_labels(mecscale_1 = "brainstem",
#                         mecscale_2 = "Entrainment",
#                         mecscale_3 = "Memory", 
#                         mecscale_4 = "Conditioning",
#                         mecscale_5 = "Imagery",
#                         mecscale_6 = "Contagion", 
#                         mecscale_7 = "Expectancy",
#                         mecscale_8 = "Appraisal", 
#                   reg.use_1 = "Regulatory Use Probability")
```

All measures showed appropraite reliability 
```{r s2alphas}

psych::alpha(dplyr::select(s2, deq_1_1:deq_1_4))$total$raw_alpha
psych::alpha(dplyr::select(s2, deq_2_1:deq_2_4))$total$raw_alpha
psych::alpha(dplyr::select(s2, deq_3_1:deq_3_4))$total$raw_alpha
psych::alpha(dplyr::select(s2, rrq_1:rrq_12))$total$raw_alpha
psych::alpha(dplyr::select(s2, musebaq_1:musebaq_9))$total$raw_alpha

```

# Manipulation Check

The manipulation/induction of sadness was succesful 
```{r manipulationcheck}
S2Manipulation <- t.test(s2$PostInduction, s2$Baseline, paired = TRUE) 

apa::t_apa(S2Manipulation)

mean(s2$Baseline)
sd(s2$Baseline)
mean(s2$PostInduction)
sd(s2$PostInduction)
```

# Hypothesis Test 

A significant interaction was found. 
```{r message = FALSE}

library(sjlabelled)
s2long <- s2 %>% 
  gather(key = Timepoint,
         value = Sadness,
         factor_key = TRUE,
         PostInduction, PostListening) 

write_csv(s2long, "data/s2long.csv")
  

library(lmerTest)
library(sjPlot)

S2glmm <- lmerTest::lmer(Sadness~1 + Timepoint + rumination + Timepoint*rumination + (1 |id), data = s2long)

tab_model(S2glmm)
```

This interaction showed a larger increase in sadness for people higher in rumination 
```{r s2hypothesisplot}
sjPlot::plot_model(S2glmm,
                   type = "int",
                   mdrt.values = "meansd",
                   ci.level = NULL,
                   legend.title = "Rumination\n (- 1SD, Mean, + 1 SD)",
                   show.values = TRUE,
                   show.p = TRUE,
                   order.terms = c(1,2,3)
                   ) + 
  ggplot2::theme(title = element_blank())+ 
  ggpubr::theme_pubr(legend = "right")
```

The simple effects showed that sadness increased for all levels of rumunation 
```{r simpleslopes}

minusrum <- mean(s2$rumination, na.rm = TRUE)-sd(s2$rumination, na.rm = TRUE)
plusrum <- mean(s2$rumination, na.rm = TRUE)+sd(s2$rumination, na.rm = TRUE)
meanrum <- mean(s2$rumination, na.rm = TRUE)


s2SimpleList <- list(rumination = c(minusrum, plusrum, meanrum), Timepoint = c("Baseline", "PostInduction", "PostListening"))

s2SimpleSlopes <- emmeans::emmeans(S2glmm, ~rumination*Timepoint, at = s2SimpleList)

emmeans::contrast(s2SimpleSlopes, "pairwise", by = "rumination")
```

