---
title: "Study Two: Exploratorty Data Analysis (Music)"
author: "joellarwood"
date: "2019-09-30"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

 
# Exploring correaltions with rumination 

```{r rumcor, message = FALSE}
library(tidyverse)
library(tidytext)

takeone <- function(x, na.rm = TRUE)(x - 1)

s2explore <- read_csv(here::here("data", "MusicEmotionRegulation_November18_Prolific_Processed.csv")) %>% 
  mutate(rumsplit = if_else(.$rumination < median(rumination, na.rm = TRUE), 
                            "Low", "High")) %>%   
  mutate_at(.vars = vars(mecscale_1:mecscale_8), 
             takeone) %>% 
    dplyr::mutate(brainstem = mecscale_1,
                        Entrainment = mecscale_2,
                        Memory = mecscale_3, 
                        Conditioning = mecscale_4,
                        Imagery = mecscale_5, 
                        Contagion = mecscale_6, 
                        Expectancy = mecscale_7,
                        Appraisal = mecscale_8) %>% 
  mutate(LikelyUse = if_else(reg.use_1 < median(reg.use_1, na.rm = TRUE), 
                             0, 
                             1))  %>% 
  mutate_at(c("brainstem", "Entrainment", "Memory", "Conditioning", "Imagery", "Contagion", "Expectancy", "Appraisal" ), 
            funs(recode(., "0" = "No", "1" = "Yes" )))
```

##Correlations between traits and BRECVEMA 

```{r s1correaltions}

library(apaTables)

apaTables::apa.cor.table(data = select(s2explore, 
                                       rumination, 
                                       musebaq, 
                                       valence, 
                                       energy), 
                         filename = "docs/s1correlations.doc")

```


```{r s1spotify, message = FALSE, warning = FALSE}

library(ggsci)
library(ggpubr)

ggpubr::ggscatterhist(s2explore,
                      x = "valence",
                      y = "energy",
                      palette = "simpsons",
                      color = "rumsplit",
                      fill = "rumsplit",
                      size = 3,
                      legend = "right",
                      xlab = "Spotify valence metric",
                      ylab = "Spotify energy metric",
                      conf.int = TRUE,
                      margin.params = list(fill = "rumsplit"),
                      legend.title = "Rumination \nScore",
                      xlim = c(0, 1),
                      ylim = c(0, 1),
                      mean.point = FALSE) 

```




# Analyse Lyrics
```{r study2JoinLyrics}


S2Lyrics <- read_csv(here::here("data", "MusicEmotionRegulation_November18_Prolific_Lyrics.csv")) %>% 
  drop_na(lyric) %>% 
  tidytext::unnest_tokens(word, lyric) %>% 
  anti_join(stop_words) %>% #only include meaningful words 
  mutate(StemWord = SnowballC::wordStem(word)) # this gets the stems of the word, I might want it later on but here for reference at the moment 

sadwords <- get_sentiments(lexicon = "nrc") %>% 
  filter(sentiment == "sadness") %>% 
  mutate(sad = T, 
         StemWord = SnowballC::wordStem(word)) # this gets the stems of the word, I might want it later on but here for reference at the moment 


S2SentimentJoin <- S2Lyrics %>% 
  left_join(sadwords, by = "word")

S2LyricSadness <- S2SentimentJoin %>%  
  group_by(track_uri) %>% 
  summarise(wordcount = n(), 
            sadwords = sum(sad, na.rm = T)) %>% 
  mutate(sadproportion = sadwords/wordcount)


s2ExploreMusicSentimentJoined <- s2explore  %>% 
  left_join(S2LyricSadness, by = "track_uri") %>% 
  drop_na(track_uri) %>% 
  mutate(DummyMode = if_else(mode == "major", 1, 0), 
         Song_Artist = glue::glue("{track_name} by {artist_name}"))

s2ExploreMusicSentimentJoined %>% 
  select(danceability, 
         energy, 
         instrumentalness, 
         valence, 
         tempo, 
         duration_ms, 
         sadproportion, 
         wordcount
         ) %>%
  write_csv(here::here("data", "MusicEmotionRegulation_November18_Prolific_MusicFeatures.csv"))

s2ExploreMusicSentimentJoined %>% 
  select(danceability, 
         energy, 
         instrumentalness, 
         valence, 
         tempo, 
         duration_ms, 
         sadproportion, 
         wordcount, 
         Baseline:PostListening, 
         rumination:LikelyUse
         ) %>%
  write_csv(here::here("data", "MusicEmotionRegulation_November18_Prolific_MusicFeatures_SelfReport.csv"))

```

<!-- # Cluster analysis  -->

<!-- K means - valence and energy -->

<!-- Number of clusters indicated as 3 -->
<!-- NOTE: Cluster labels will change on each -->
<!-- ```{r s1cluster} -->
<!-- library(NbClust) -->
<!-- library(factoextra) -->

<!-- VA <- drop_na(select(s2explore, valence, energy, id)) -->

<!-- factoextra::fviz_nbclust(NbClust(select(VA, -id), distance = "euclidean", method = "kmeans")) + theme_minimal() + ggtitle("NbClust's optimal number of clusters") -->

<!-- VAclust <- VA %>%  -->
<!--   mutate(KmeansCluster = fct_recode(factor(kmeans(select(VA, -id), 3)$cluster))) -->

<!-- s1clusters <- full_join(s1explore, select(VAclust, id, KmeansCluster), by = "id") %>% drop_na(KmeansCluster) -->

<!-- write_csv(s1clusters, "data/s1clusters.csv") -->
<!-- ``` -->
